Create a new API request /app
ElevenPaths/tacyt-sdk-python pull request #14
Opened 2020-02-10 17:24 UTC by fnavarrogonzalez

2020-02-20 07:39 UTC, javiersanzfre commented on tacyt_sdk/authorization/response.py
> +    It consists of a "data" and an "error" elements. Although normally only one
We also added a new field "args" informing about the fields than hav the error
Example:
`{
  "error": {
    "code": 401,
    "message": "Missing parameter in API call",
    "args": "uniqueOriginId, uniqueVersionId, platform, title, appURL"
  }
}`

2020-02-20 08:48 UTC, fnavarrogonzalez commented on tacyt_sdk/authorization/response.py
> +    It consists of a "data" and an "error" elements. Although normally only one
A new args argument is added.

2020-02-20 09:45 UTC, dgseten requested changes
Only a few comments. Good job Fran, the source code is fantastic.

2020-02-20 09:45 UTC, dgseten commented on tacyt/TacytApp.py
>      def getEngineVersion(self, date=None, engineId=None, lang=None):
Are we going to maintain the camelCase format?

2020-02-20 09:45 UTC, dgseten commented on tacyt/TacytApp.py
>      def uploadURL(self, urls, tagNames=None):
Are we going to maintain the camelCase format?

2020-02-20 09:45 UTC, dgseten commented on tacyt/TacytApp.py
> +    @staticmethod
(Only a suggestion)
Why not pass the proxy and the host during the client creation? In my opinion is more intuitive. In addition, if we want to create several clients for different host we could do...

2020-02-20 09:45 UTC, dgseten commented on tacyt_sdk/api_requests/filter_request.py
> +    def __init__(self, request_type=None, filter_=None, page=None,
Only a doubt..
why the las underscore in filter_ ?

2020-02-20 09:45 UTC, dgseten commented on tacyt_sdk/api_requests/market_app_request.py
> +    def as_dict(self):
(Idea)
Since all the requests objects implements the as_dict method we could use interfaces from abc module

2020-02-20 09:45 UTC, dgseten commented on tacyt_sdk/authorization/auth.py
> +                               body=None, utc=None):
Add body in docstring

2020-02-20 09:45 UTC, dgseten commented on tacyt_sdk/authorization/auth.py
> +            print(headers)
print

2020-02-20 09:45 UTC, dgseten commented on tacyt_sdk/authorization/auth.py
> +                                                  self.API_UPLOAD_URL,
Not defined in this class, I guess that it's obtained via heritage. Define as None in this base class?

2020-02-20 09:45 UTC, dgseten commented on tacyt_sdk/client.py
> +
1 line

2020-02-20 09:45 UTC, dgseten commented on tacyt_sdk/client.py
> +                              body=result.as_dict())
same

2020-02-20 09:45 UTC, dgseten commented on tacyt_sdk/filter_model.py
> +    def __init__(self, id_=None, name=None, description=None, weight=None,
I would use filter_id

2020-02-20 14:51 UTC, fnavarrogonzalez commented on tacyt/TacytApp.py
>      def create_filter(self, filter):
legacy interface, it should keep the variable as it is, in case someone is calling it with parameter=value, but this will be removed in further versions.

2020-02-20 14:52 UTC, fnavarrogonzalez commented on tacyt/TacytApp.py
>      def getEngineVersion(self, date=None, engineId=None, lang=None):
Same, legacy backward compatibility, this is class is just for backward compatiblity during this version, remove it in further versions after show some deprecates warnings.
Use TacytClient is the new way with snake_case.

2020-02-20 14:55 UTC, fnavarrogonzalez commented on tacyt_sdk/api_requests/compare_request.py
> +class CompareRequest:
This is true for python2/3. 
Note that in python3 pylint give you an advice to remove object inherence since all class herence this class.

2020-02-20 14:55 UTC, fnavarrogonzalez commented on tacyt_sdk/api_requests/filter_request.py
> +    def __init__(self, request_type=None, filter_=None, page=None,
filter is a built_in function

2020-02-20 15:00 UTC, fnavarrogonzalez commented on tacyt_sdk/authorization/auth.py
> +                                                  self.API_UPLOAD_URL,
Nope, coming from a bad refactor.

2020-02-20 15:20 UTC, fnavarrogonzalez commented on tacyt/TacytApp.py
> +    @staticmethod
The proxy is pass throw the constructor but not the host that is taken from version class.
It could be good pass proxy, host and client but I will suggest extended after remove this backward compatiblity that uses staticmethod and class variables.

2020-02-21 10:05 UTC, fnavarrogonzalez commented on tacyt_sdk/api_requests/market_app_request.py
> +    def as_dict(self):
Its complicate to do a fast backward compatibility usage of abc classes without external utilities.

2020-02-25 07:43 UTC, ivan11paths commented on tacyt/TacytApp.py
> +@deprecated(version=Version.API_VERSION, action="once",
We agreed to format with 180 characters

2020-02-25 08:16 UTC, ivan11paths commented on tacyt_sdk/api_requests/filter_request.py
> +    def __init__(self, request_type=None, filter_=None, page=None,
Please, use filter_obj

2020-02-25 08:38 UTC, dgseten approved these changes

2020-02-25 08:42 UTC, ivan11paths requested changes

2020-02-25 08:42 UTC, ivan11paths commented on README.md
> +all_tags = api.list_tags()
You should rename 'api' for 'tacyt_client'

2020-02-25 08:42 UTC, ivan11paths commented on tacyt/TacytApp.py
> +@deprecated(version=Version.API_VERSION, action="once",
Formatted with 180 chars. And, you should indicate the VERSION when you deprecated not the now version

2020-02-25 08:42 UTC, ivan11paths commented on tacyt/TacytApp.py
> +    def search_apps(self, query, numberPage=None, maxResults=None,
Why you remove documentation of all methods?

2020-02-25 08:42 UTC, ivan11paths commented on tacyt_sdk/api_requests/compare_request.py
> +class CompareRequest(object):
Is it compatible with old versions to move these files to other folder?

2020-02-25 08:42 UTC, ivan11paths commented on tacyt_sdk/api_requests/upload_url_request.py
> +Copyright (C) 2019 Eleven Paths
Unify all copyright texts

2020-02-27 15:00 UTC, ivan11paths requested changes

2020-02-27 15:00 UTC, ivan11paths commented on tacyt_sdk/authorization/auth.py
> +        sha1_hash = hmac.new(ensure_binary(self.secret_key),
Please format into line with 180 chars

2020-02-27 16:33 UTC, ivan11paths approved these changes

2020-02-27 16:33 UTC, merged