(Resolves #110650) Add new mandatory fields in API new market
ElevenPaths/tacyt-sdk-python pull request #20
Opened 2020-03-26 12:25 UTC by javiersanzfre

2020-03-26 12:27 UTC, fnavarrogonzalez approved these changes

2020-03-26 12:28 UTC, fnavarrogonzalez commented on tacyt_sdk/api_requests/market_app_request.py
> +    if field_name == "find_date":
this is automatically converted by to_camel_case, the only problem is when you have acronyms that are upper case.
So it can be removed.

2020-03-27 14:08 UTC, ivan11paths requested changes
You should fix the comment create by Fran

2020-03-30 07:41 UTC, ivan11paths approved these changes

2020-03-30 07:42 UTC, merged